### ISSUE TITLE
Build out SDK components

### ISSUE THREAD

**Issue by raymondpulver** [zerodao-finance/zero-protocol#22]
SDK should include functions for the following:

- Use ren-js to compute deposit address for a given TransferRequest
- Use lib/rpc/btc to check deposit address for a successful deposit
    - Add facilities to poll the deposit address until this occurs
  
- Implement way to supply your own adapter to persist TransferRequest to localStorage, redis, or whatever, depending on environment, in order to resume a RenVM mint in the case that it is interrupted
    - Abstract this concept into a base class and give an implementation of the LocalStoragePersistenceAdapter and MemoryAdapter (only persist in memory) for now
- Submit RenVM compatible payload to the RenVM network, assemble payload from a TransferRequest then send it up to RenVM via the ren-js SDK
- Compute RenVM mint transaction hash
- Query transaction hash for RenVM mint to retrieve the different parameters to the repayLoan function (which are passed down to the Gateway.mint function in this function call in ZeroController.sol)
- Use libp2p network to broadcast a TransferRequest object to be received by a keeper
- Function which accepts a providerOrSigner object and returns an object of ethers.js Contract instances for each component of the system

Create mocks for RenVM network for the functions which it queries, create mocks for BTC RPC adapter to simulate a deposit being made, then implement a test suite by extending test/test.ts to simulate the entire workflow locally using the libp2p adapters as well

**Comment by p1ge0nh8er** [comment]
> Use ren-js to compute deposit address for a given TransferRequest
https://github.com/zerodao-finance/zero-protocol/blob/develop/lib/util/renvm.ts#L18 - this function generates the deposit address. Do you want to replace this?

**Comment by p1ge0nh8er** [comment]
Was reviewing the documentation of renvm, and this looked concerning - https://renproject.github.io/ren-client-docs/ren-js/best-practices/ui-best-practices#5-storing-orders
For users only transacting via UI, if they clear the localStorage then resuming their transfers will become difficult. We could utilize gun db(works in browser and node), to store their transferRequests, which is tied to their bitcoin address?

Gun db: https://gun.eco (decentralized graph db)

**Comment by raymondpulver** [comment]
> > Use ren-js to compute deposit address for a given TransferRequest
> 
> https://github.com/zerodao-finance/zero-protocol/blob/develop/lib/util/renvm.ts#L18 - this function generates the deposit address. Do you want to replace this?

We would want to get this in TypeScript and include it in the functionality. But, if it exists in the latest version of the ren-js SDK as a submodule that we can import directly, then I would prefer to rely on that library so we do not have our own implementation. I have not kept up with the status of ren-js lately so it is worth a look to see if this can be done.

**Comment by raymondpulver** [comment]
> Was reviewing the documentation of renvm, and this looked concerning - https://renproject.github.io/ren-client-docs/ren-js/best-practices/ui-best-practices#5-storing-orders
> For users only transacting via UI, if they clear the localStorage then resuming their transfers will become difficult. We could utilize gun db(works in browser and node), to store their transferRequests, which is tied to their bitcoin address?
> 
> Gun db: https://gun.eco (decentralized graph db)

Merged the GunDB PR
