### ISSUE TITLE
[FEATURE] ZeroController#meta

### ISSUE THREAD

**Issue by raymondpulver** [zerodao-finance/zero-protocol#47]
Implement a function to be called onlyUnderwriter in the ZeroController which should measure gas usage from start to finish, send a tx to IModule(module).receiveMeta(from, asset, nonce, data), get the on chain value of gas usage in terms of renBTC, apply the same fee as a loan, then send a tx IModule(module).repayMeta(gasValueAndFee), and compare balance before and after to confirm that renBTC (or whatever asset is) acquired is greater than gasValueAndFee, then depositAll() to increase the value of zeroBTC proportionally by sending renBTC into the vault.

average(gasValueInETHWithoutFee, gasValueInETHWithFee) should be repaid to keeper via permissionedEther the same as in a loan transaction, so a keeper can benefit in native currency

The function signature should look like 

`function meta(address from, address asset, address module, uint256 nonce, bytes memory data, bytes memory signature) public onlyUnderwriter`

The JS SDK library should feature a MetaRequest class designed with similar structure to the TransferRequest, which should do all of the heavy lifting for implementers wishing to make use of zeroDAO to incentivize keepers to forward tx execution on behalf of an end user

**Comment by raymondpulver** [comment]
Part of designing this will be identifying the parameters to the @renproject/ren burnAndRelease function. It is important to identify the workflow they expect and what the payload to RenVM will have to look like, to understand how to design the ZeroController upgrade

**Comment by v16s** [comment]
Reopened until MetaRequest is finished
