### ISSUE TITLE
Implement libp2p signaling protocol

### ISSUE THREAD

**Issue by raymondpulver** [zerodao-finance/zero-protocol#6]
The libp2p connection should be able to be constructed by a function exposed by the top level require('zero-protocol').createZeroConnection which returns a require('zero-protocol').ZeroConnection instance, a subclass of the libp2p object which should contain functions:

keeper mode:
  - advertiseAsKeeper(address)
  - handleTransferRequest({ peerInfo, TransferRequest, signature })
 
user mode:
  - subscribeKeepers() (begin collecting keeper objects { peerInfo, address } store in memory)
  - unsubscribeKeepers() (stop collecting)
  -  publishTransferRequest(TransferRequest) (wait to have one keeper in cache at least, dial directly to all keepers, wait for acknowledgement of tx dispatch)

**Comment by p1ge0nh8er** [comment]
For acknowledgement of tx dispatch, I think we should use an internal transferRequest uuid mechanism, which is injected into the transfer request. When the user subscribes to all tx dispatches, they should be able to filter out the acks based on the tx only _they_ published. What do you think?

**Comment by p1ge0nh8er** [comment]
Relevant branch: feat/libp2p-mocks

**Comment by raymondpulver** [comment]
Other users should not receive messages for tx dispatch. The naming of the functions implies pubsub, and that is what we did for the previous version, but for this version, a keeper should publish his existence and ETH address he will dispatch from, then users will collect keepers on the network, and then when a user wants to do a transfer, he dials the keepers directly via their peerId

**Comment by raymondpulver** [comment]
There should not be a random UUID for a TransferRequest it should only be the EIP712Digest if anything

**Comment by p1ge0nh8er** [comment]
Fixed in #10
