### ISSUE TITLE
Create docker container via docker-compose.yaml file and host libp2p-webrtc-star

### ISSUE THREAD

**Issue by raymondpulver** [zerodao-finance/zero-protocol#8]
Reference the original 0confirmation/0confirmation repo to see the Docker image made for this purpose

The issue with the previous deployment was the failure to use network_mode: 'host' on the service definition, thus creating an NAT issue where WebRTC could not accomplish hole punching for users on a VPN (or mobile)

**Comment by p1ge0nh8er** [comment]
I have a couple of questions
- For development mode, do you require SSL?
- What architecture are we running (so that I can get a prod container ready)?

**Comment by raymondpulver** [comment]
Yes we need SSL to test a staging server but the local deployment will use mocks and there will be no actual p2p happening

We will be running x64 Ubuntu with 2gb of memory is fine. We will likely deploy on a single server.

**Comment by p1ge0nh8er** [comment]
Got it. Can we close this?
